disabled_rules:
- line_length
- void_function_in_ternary
- control_statement
- todo
- type_name
- notification_center_detachment

excluded:
- Carthage
- Pods

function_body_length:
    warning: 40
    error: 50
